# Generated by Django 2.2.3 on 2019-09-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cemetery_name', models.CharField(max_length=100)),
                ('cemetery_address', models.CharField(max_length=300)),
                ('church_name', models.CharField(max_length=100)),
                ('church_address', models.CharField(max_length=300)),
                ('born_date', models.DateField()),
                ('death_date', models.DateField()),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
