# Generated by Django 2.2.3 on 2019-09-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_obit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obit',
            options={'ordering': ['-death_date']},
        ),
    ]
